test_data<-read.table("./UCI HAR Dataset/test/X_test.txt")
train_data<-read.table("./UCI HAR Dataset/train/X_train.txt")
clnames<-t(read.table("./UCI HAR Dataset/features.txt"))
cnames<-cbind("Subject","Activity",clnames)
all_data<-rbind(test_data,train_data)
test_activity<-read.table("./UCI HAR Dataset/test/y_test.txt")
train_activity<-read.table("./UCI HAR Dataset/train/y_train.txt")
test_subject<-read.table("./UCI HAR Dataset/test/subject_test.txt")
train_subject<-read.table("./UCI HAR Dataset/train/subject_train.txt")
all_activity<-rbind(test_activity,train_activity)
all_subject<-rbind(test_subject, train_subject)
all_data<-cbind(all_subject,all_activity,all_data)
colnames(all_data)<-cnames[2,]
activity_label<-read.table("./UCI HAR Dataset/activity_labels.txt")
colnames(activity_label)<-c("Activity","Activity_Label")
all_data<-merge(activity_label,all_data)
filtered_data <- all_data[,grep("[Mm]ean|[Ss][Tt][Dd]|Activity_Label|Subject", names(all_data))]
attach(filtered_data)
tidy_data <- aggregate(filtered_data, by=list(Activity_Label, Subject), FUN = "mean")
detach(filtered_data)
tidy_data <- subset(tidy_data, select = -c(Group.2,Activity_Label))
colnames(tidy_data)[1]<-"Activity"
names(tidy_data)<-gsub("_|-|\\(|\\)|,", "", names(tidy_data));names(tidy_data)<-gsub("tGravity", "Timegravity", names(tidy_data))
names(tidy_data)<-gsub("Acc", "Acceleration", names(tidy_data));names(tidy_data)<-gsub("Gyro", "Gyroscope", names(tidy_data))
names(tidy_data)<-gsub("Freq", "Frequency", names(tidy_data));names(tidy_data)<-gsub("std", "StandardDeviation", names(tidy_data))
names(tidy_data)<-gsub("tB", "TimeB", names(tidy_data));names(tidy_data)<-gsub("fB", "FrequencyB", names(tidy_data))
names(tidy_data)<-gsub("Mag", "Magnitude", names(tidy_data));names(tidy_data)<-gsub("mean", "Mean", names(tidy_data))
names(tidy_data)<-gsub("angle", "Angle", names(tidy_data));names(tidy_data)<-gsub("gravity", "Gravity", names(tidy_data))